import nbformat


def build_notebook(cells: list[dict], paper_title: str) -> nbformat.NotebookNode:
    """Convert a list of cell dicts from the LLM into a valid .ipynb notebook."""
    nb = nbformat.v4.new_notebook()

    nb.metadata = {
        "colab": {
            "provenance": [],
            "name": f"{paper_title} — Tutorial",
        },
        "kernelspec": {
            "name": "python3",
            "display_name": "Python 3",
        },
        "language_info": {
            "name": "python",
            "version": "3.10.0",
        },
    }

    # Title cell
    nb.cells.append(
        nbformat.v4.new_markdown_cell(
            f"# {paper_title} — Tutorial Notebook\n\n"
            "This notebook was auto-generated by **Paper2Notebook**. "
            "It implements key algorithms and methodology from the paper as a tutorial."
        )
    )

    # Setup / install cell
    nb.cells.append(
        nbformat.v4.new_code_cell(
            "# Setup: install required packages\n"
            "!pip install -q numpy matplotlib seaborn scipy scikit-learn"
        )
    )

    # Add all LLM-generated cells
    for cell in cells:
        cell_type = cell.get("cell_type", "markdown")
        source = cell.get("source", "")
        if cell_type == "code":
            nb.cells.append(nbformat.v4.new_code_cell(source))
        else:
            nb.cells.append(nbformat.v4.new_markdown_cell(source))

    return nb
