import { test, expect } from "@playwright/test";
import path from "path";
import fs from "fs";

const SCREENSHOT_DIR = path.join(__dirname, "..", "screenshots", "e2e-flow");

test.beforeAll(() => {
  fs.mkdirSync(SCREENSHOT_DIR, { recursive: true });
});

test.describe("Full User Flow — E2E", () => {
  test("complete flow: upload PDF → generate → preview → download", async ({
    page,
  }) => {
    // Mock the backend API to return a fake notebook
    const mockNotebook = {
      notebook: {
        nbformat: 4,
        nbformat_minor: 5,
        metadata: {
          colab: { provenance: [], name: "Test — Tutorial" },
          kernelspec: { name: "python3", display_name: "Python 3" },
          language_info: { name: "python", version: "3.10.0" },
        },
        cells: [
          {
            cell_type: "markdown",
            metadata: {},
            source: "# Test Paper — Tutorial Notebook\n\nThis notebook was auto-generated by **Paper2Notebook**.",
          },
          {
            cell_type: "code",
            metadata: {},
            source: "# Setup: install required packages\n!pip install -q numpy matplotlib",
            execution_count: null,
            outputs: [],
          },
          {
            cell_type: "markdown",
            metadata: {},
            source: "## Introduction\n\nThis paper explores transformer architectures.",
          },
          {
            cell_type: "code",
            metadata: {},
            source: "import numpy as np\nimport matplotlib.pyplot as plt\n\n# Implement attention mechanism\ndef attention(Q, K, V):\n    scores = np.dot(Q, K.T)\n    return np.dot(scores, V)",
            execution_count: null,
            outputs: [],
          },
        ],
      },
    };

    await page.route("**/api/generate", async (route) => {
      await route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify(mockNotebook),
      });
    });

    // Step 1: Navigate to homepage
    await page.goto("http://localhost:3000");
    await page.screenshot({
      path: path.join(SCREENSHOT_DIR, "step-01-homepage.png"),
    });
    await expect(page.getByTestId("page-title")).toBeVisible();

    // Step 2: Enter API key
    await page.getByTestId("api-key-input").fill("sk-test-key-12345");
    await page.screenshot({
      path: path.join(SCREENSHOT_DIR, "step-02-api-key.png"),
    });

    // Step 3: Upload PDF
    const testPdfPath = path.join(__dirname, "..", "fixtures", "test.pdf");
    await page.getByTestId("pdf-file-input").setInputFiles(testPdfPath);
    await page.screenshot({
      path: path.join(SCREENSHOT_DIR, "step-03-pdf-uploaded.png"),
    });
    await expect(page.getByTestId("file-name")).toBeVisible();

    // Step 4: Click Generate
    const submitBtn = page.getByTestId("submit-button");
    await expect(submitBtn).toBeEnabled();
    await submitBtn.click();

    await page.screenshot({
      path: path.join(SCREENSHOT_DIR, "step-04-loading.png"),
    });

    // Step 5: Wait for notebook preview
    await expect(page.getByTestId("notebook-preview")).toBeVisible({
      timeout: 15000,
    });
    await page.screenshot({
      path: path.join(SCREENSHOT_DIR, "step-05-notebook-preview.png"),
    });

    // Step 6: Verify safety warning banner
    await expect(page.getByTestId("safety-warning-banner")).toBeVisible();
    await expect(page.getByTestId("safety-warning-banner")).toContainText(
      "AI-generated code"
    );

    // Step 7: Click Download
    const downloadPromise = page.waitForEvent("download");
    await page.getByTestId("download-button").click();
    const download = await downloadPromise;
    await page.screenshot({
      path: path.join(SCREENSHOT_DIR, "step-06-download.png"),
    });

    // Step 8: Validate downloaded file
    expect(download.suggestedFilename()).toMatch(/\.ipynb$/);
    const downloadPath = await download.path();
    if (downloadPath) {
      const content = fs.readFileSync(downloadPath, "utf-8");
      const nb = JSON.parse(content);
      expect(nb.nbformat).toBe(4);
      expect(nb.cells.length).toBeGreaterThanOrEqual(2);
    }
  });
});
